### PR TITLE
Update faiss description

### PR DESCRIPTION
**Pull request by Tps-F**
Additions from #92 
If the translation is incorrect, I'll correct it.

### CODE REVIEW

**Comment by fire** [comment]
The english part is ok.

**Review by fumiama — APPROVED** [review]

**Review by fumiama — CHANGES_REQUESTED** [review]
I think we should stress `manually` because the version decision has been added to `requirements.txt`. For Chinese version, it can be
```
`MacOS`下`faiss 1.7.2`版本会导致抛出段错误，在手动安装时请使用命令`pip install faiss-cpu==1.7.0`指定使用`1.7.0`版本
```
日本語の場合は（語彙の適切化する修正が要るかも）
```
`faiss 1.7.2`は`macOS`で`Segmentation Fault: 11`を起こすので、マニュアルインストールする場合は、 `pip install faiss-cpu==1.7.0`を実行してください。
```
英語は略しておきますが、ともに変更しましょう。

**Comment by fire** [comment]
Probably want to squash into one commit when ready.

https://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request

**Comment by fumiama** [comment]
> Probably want to squash into one commit when ready. However, I am not staff of this development team.
> 
> https://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request

Don't mind. We will do that.

**Review by fumiama — APPROVED** [review]

**Comment by Tps-F** [comment]
@fumiama Is there anything I should fix?
I want to run the check again.

**Comment by fumiama** [comment]
That's weird. I had re-run all failed jobs.

**Pull request merged**
